DROP TABLE IF EXISTS chat_friend;
CREATE TABLE chat_friend
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    from_user_id BIGINT NOT NULL REFERENCES users(id),
    from_blocked BOOL NOT NULL DEFAULT FALSE,
    to_user_id BIGINT NOT NULL REFERENCES users(id),
    to_blocked BOOL NOT NULL DEFAULT FALSE,
    active BOOL NOT NULL DEFAULT FALSE,
    -- IT CAN BE USED FOR KNOWING WHEN DO THEY REALLY BECOME FRIENDS
    -- WHEN DO THEY BLOCKED AND UNBLOCKED EACH OTHER
    active_date TIMESTAMP WITHOUT TIME ZONE,
    -- WHEN WAS FRIEND REQUEST SEND
    insert_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    -- WHEN WAS LAST UPDATE?
    update_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX ON chat_friend (GREATEST(from_user_id,to_user_id), LEAST(from_user_id,to_user_id));

CREATE TRIGGER update_date BEFORE UPDATE ON chat_friend FOR EACH ROW EXECUTE FUNCTION trigger_update_date();
