DROP TYPE IF EXISTS CHAT_MEDIA_CONTENT_TYPE CASCADE;
CREATE TYPE CHAT_MEDIA_CONTENT_TYPE AS ENUM
(
    'image',
    'audio',
    'video'
);
DROP TABLE IF EXISTS chat_media;
CREATE TABLE chat_media
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    hash TEXT,
    user_id BIGINT NOT NULL REFERENCES users(id),
    uploaded BOOL,
    content_type CHAT_MEDIA_CONTENT_TYPE,
    insert_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ON chat_media(hash)
